languageCode = "zh-tw"
languageName = "ğŸ‡¹ğŸ‡¼ ä¸­æ–‡ (å°ç£)"
languageDirection = "ltr"
weight = 1
hasCJKLanguage = true

title = "Tomy's Blog"
copyright = '<a href="{{< relref "copyright" >}}" class="hover:underline hover:decoration-primary-400 hover:text-primary-500">Copyright</a> Â© 2022 Tomy Hsieh.'

[params]
  # dateFormat = "2 January 2006"

  description = "Tomy Hsieh çš„å¥‡å¹»éƒ¨è½"
  publishDate = 2022-08-04T06:25:42+08:00

  [params.rss]
    image = "rss-image-144x144.png"
    imageWidth = 144
    imageHeight = 144
    imageDescription = "Tomy's Logo"
    ttl = 60

[author]
  name = "Tomy Hsieh"
  image = "img/tomy.png"
  # headline = "I'm only human"
  bio = "åœ¨å°ç£æ··ä¸ä¸‹å»é€ƒåˆ°ç¾åœ‹çš„ç„¡æ¥­ç¢¼è¾²<br/>ç›®å‰æ­£åœ¨æ‰¾ 2024 Internï¼Œæ­¡è¿é»æ“Š LinkedIn è¯ç¹«è³æˆ‘å£é£¯åƒï¼šï¼‰"
  links = [
  #   { email = "mailto:hello@your_domain.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/tomy0000000" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
    { instagram = "https://instagram.com/tomy0000000" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://linkedin.com/in/tomy0000000" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
    { twitter = "https://twitter.com/tomy0000000" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
  ]
