# https://pre-commit.ci/#configuration
ci:
  autoupdate_branch: "develop"
  autoupdate_commit_msg: "ðŸŽ› ci: pre-commit autoupdate"
# https://pre-commit.com/#pre-commit-configyaml---top-level
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: layouts/_markup/render-link.html
      - id: mixed-line-ending
      - id: trailing-whitespace
